name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SQLite3 dev
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev sqlite3

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build
        run: zig build

      - name: Unit tests
        run: zig build test

      - name: Integration tests
        run: zig build test-integration